version: 2

defaults: &defaults
  docker:
    - image: circleci/node:carbon
  working_directory: ~/project

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "yarn.lock" }}
            - dependencies-cache

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/project
          paths: .

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Linter
          command: yarn lint:ci

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Test
          command: yarn test:ci

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Deploy application
          command: yarn deploy

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
